create table book (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);
insert into book (name) values ('Nacho Libre');
insert into book (name) values ('Detour');
insert into book (name) values ('Tartuffe (Herr Tartüff)');
insert into book (name) values ('Recoil');
insert into book (name) values ('Barfly');
insert into book (name) values ('Undertow (Contracorriente)');
insert into book (name) values ('Eyes of Tammy Faye, The');
insert into book (name) values ('Gypsy');
insert into book (name) values ('Lon Chaney: A Thousand Faces');
insert into book (name) values ('He Who Dares');
insert into book (name) values ('Beautiful Life, A');
insert into book (name) values ('Jolson Story, The');
insert into book (name) values ('Red Heat');
insert into book (name) values ('Hounds, The');
insert into book (name) values ('Die Another Day');
insert into book (name) values ('Annie Oakley');
insert into book (name) values ('Battle of Shaker Heights, The');
insert into book (name) values ('Favorite Deadly Sins');
insert into book (name) values ('Experiment in Terror');
insert into book (name) values ('As I Lay Dying');
insert into book (name) values ('Uncounted: The New Math of American Elections');
insert into book (name) values ('Kiss Before Dying, A');
insert into book (name) values ('Role Models');
insert into book (name) values ('Tyler Perry''s A Madea Christmas');
insert into book (name) values ('Painting Sellers, The (Taulukauppiaat)');
insert into book (name) values ('Boulevard');
insert into book (name) values ('Bigger, Stronger, Faster*');
insert into book (name) values ('Runaway');
insert into book (name) values ('Taistelu Näsilinnasta 1918');
insert into book (name) values ('Hotel Pacific (Zaklete rewiry)');
insert into book (name) values ('When Time Ran Out... (Day the World Ended, The)');
insert into book (name) values ('Torment (Hets)');
insert into book (name) values ('Aftermath');
insert into book (name) values ('The Hunchback of Paris');
insert into book (name) values ('Drive Thru');
insert into book (name) values ('Pharaoh''s Army');
insert into book (name) values ('Children Underground');
insert into book (name) values ('Leonard Part 6');
insert into book (name) values ('Generation War');
insert into book (name) values ('Chappie');
insert into book (name) values ('Christmas Carol, A');
insert into book (name) values ('The Humanoid');
insert into book (name) values ('Cheeky Girls');
insert into book (name) values ('Gamera vs. Jiger');
insert into book (name) values ('Bed & Breakfast: Love is a Happy Accident (Bed & Breakfast)');
insert into book (name) values ('L''antisémite');
insert into book (name) values ('Eastern Promises');
insert into book (name) values ('Abbott and Costello Meet the Keystone Kops');
insert into book (name) values ('Cloud-Capped Star, The (Meghe Dhaka Tara)');
insert into book (name) values ('Holy Matrimony');
insert into book (name) values ('Métastases');
insert into book (name) values ('Q & A');
insert into book (name) values ('Chosen One, The');
insert into book (name) values ('Riding in Cars with Boys');
insert into book (name) values ('Cheap Detective, The');
insert into book (name) values ('Power and Terror: Noam Chomsky in Our Times');
insert into book (name) values ('Mayerling');
insert into book (name) values ('Anguish (Angustia)');
insert into book (name) values ('Colossal Youth (Juventude Em Marcha)');
insert into book (name) values ('Space Odyssey: Voyage to the Planets');
insert into book (name) values ('Quinceañera');
insert into book (name) values ('Hellboy II: The Golden Army');
insert into book (name) values ('Dreamland');
insert into book (name) values ('Project Nim');
insert into book (name) values ('Lili''s Apron');
insert into book (name) values ('Taking Care of Business');
insert into book (name) values ('Brigham Young');
insert into book (name) values ('Visitor, The');
insert into book (name) values ('Our Man in Havana');
insert into book (name) values ('Ju-on: White Ghost');
insert into book (name) values ('Coluche, l''histoire d''un mec');
insert into book (name) values ('Flu');
insert into book (name) values ('Infinity');
insert into book (name) values ('Hysterical Blindness');
insert into book (name) values ('Benigni');
insert into book (name) values ('Solomon Kane');
insert into book (name) values ('Irreversible (Irréversible)');
insert into book (name) values ('Go Fish');
insert into book (name) values ('Viridiana');
insert into book (name) values ('Delicatessen');
insert into book (name) values ('Dom Hemingway');
insert into book (name) values ('S.O.S. Eisberg');
insert into book (name) values ('Black Rain');
insert into book (name) values ('Louis C.K.: Oh My God');
insert into book (name) values ('Runaway');
insert into book (name) values ('8th Wonderland');
insert into book (name) values ('Let''s Get Lost');
insert into book (name) values ('Detective, The (C+ jing taam)');
insert into book (name) values ('Exorcism of Emily Rose, The');
insert into book (name) values ('Bird People');
insert into book (name) values ('Ski Party');
insert into book (name) values ('7 Women (a.k.a. Seven Women)');
insert into book (name) values ('Cavemen');
insert into book (name) values ('Gentle Breeze in the Village, A (Tennen kokekkô) ');
insert into book (name) values ('Merchant of Four Seasons, The (Händler der vier Jahreszeiten)');
insert into book (name) values ('Undisputed');
insert into book (name) values ('Sniper, The');
insert into book (name) values ('Evidence');
insert into book (name) values ('Walk in the Sun, A');
insert into book (name) values ('Vendetta');
